### ISSUE TITLE
头像显示有错误

### ISSUE THREAD

**Issue by frankyyzy** [frankyyzy/wxmeet#42] opened 2019-10-02 03:31 UTC
profile pictures have undefined behaviors. 
May show up wrong profile pictures when one attendee changes their available times.

**Comment by frankyyzy** [comment] 2019-10-02 03:33
how to reproduce: 
create a event, select time , share to friend, they select some time.
exit miniprogram, edit time and deselect all time. go back to profile page and go to event page again.

**Comment by frankyyzy** [comment] 2019-10-02 04:02
pictures some times doesn't load, sometimes change order while touching

**Comment by frankyyzy** [comment] 2019-12-03 07:05
turns out need to hold for a long time.

**Comment by frankyyzy** [comment] 2019-12-15 01:52
possible solution: preprocessing profile pictures

**Comment by kwkarlwang** [comment] 2019-12-15 08:39
The problem is fixed with preprocessing and html image hidden.

**Closed by kwkarlwang** 2019-12-15 08:39 UTC
Labels: bug
